name: C CI

on:
  push:
    branches: [ "main", "principal" ]
  pull_request:
    branches: [ "main", "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compilar
      run: gcc -Wall main.c -o meu_programa

    - name: Executar
      run: ./meu_programa
